MUNICIPALITIES = [
    ('', ''),
    ('Akmenės r. sav.', 'Akmenės r. sav.'),
    ('Alytaus m. sav.', 'Alytaus m. sav.'),
    ('Alytaus r. sav.', 'Alytaus r. sav.'),
    ('Anykščių r. sav.', 'Anykščių r. sav.'),
    ('Birštono sav.', 'Birštono sav.'),
    ('Biržų r. sav.', 'Biržų r. sav.'),
    ('Druskininkų sav.', 'Druskininkų sav.'),
    ('Elektrėnų sav.', 'Elektrėnų sav.'),
    ('Ignalinos r. sav.', 'Ignalinos r. sav.'),
    ('Jonavos r. sav.', 'Jonavos r. sav.'),
    ('Joniškio r. sav.', 'Joniškio r. sav.'),
    ('Jurbarko r. sav.', 'Jurbarko r. sav.'),
    ('Kaišiadorių r. sav.', 'Kaišiadorių r. sav.'),
    ('Kalvarijos sav.', 'Kalvarijos sav.'),
    ('Kauno m. sav.', 'Kauno m. sav.'),
    ('Kauno r. sav.', 'Kauno r. sav.'),
    ('Kazlų Rūdos sav.', 'Kazlų Rūdos sav.'),
    ('Kėdainių r. sav.', 'Kėdainių r. sav.'),
    ('Kelmės r. sav.', 'Kelmės r. sav.'),
    ('Klaipėdos m. sav.', 'Klaipėdos m. sav.'),
    ('Klaipėdos r. sav.', 'Klaipėdos r. sav.'),
    ('Kretingos r. sav.', 'Kretingos r. sav.'),
    ('Kupiškio r. sav.', 'Kupiškio r. sav.'),
    ('Lazdijų r. sav.', 'Lazdijų r. sav.'),
    ('Marijampolės sav.', 'Marijampolės sav.'),
    ('Mažeikių r. sav.', 'Mažeikių r. sav.'),
    ('Molėtų r. sav.', 'Molėtų r. sav.'),
    ('Neringos sav.', 'Neringos sav.'),
    ('Pagėgių sav.', 'Pagėgių sav.'),
    ('Pakruojo r. sav.', 'Pakruojo r. sav.'),
    ('Palangos m. sav.', 'Palangos m. sav.'),
    ('Panevėžio m. sav.', 'Panevėžio m. sav.'),
    ('Panevėžio r. sav.', 'Panevėžio r. sav.'),
    ('Pasvalio r. sav.', 'Pasvalio r. sav.'),
    ('Plungės r. sav.', 'Plungės r. sav.'),
    ('Prienų r. sav.', 'Prienų r. sav.'),
    ('Radviliškio r. sav.', 'Radviliškio r. sav.'),
    ('Raseinių r. sav.', 'Raseinių r. sav.'),
    ('Rietavo sav.', 'Rietavo sav.'),
    ('Rokiškio r. sav.', 'Rokiškio r. sav.'),
    ('Skuodo r. sav.', 'Skuodo r. sav.'),
    ('Šakių r. sav.', 'Šakių r. sav.'),
    ('Šalčininkų r. sav.', 'Šalčininkų r. sav.'),
    ('Šiaulių m. sav.', 'Šiaulių m. sav.'),
    ('Šiaulių r. sav.', 'Šiaulių r. sav.'),
    ('Šilalės r. sav.', 'Šilalės r. sav.'),
    ('Šilutės r. sav.', 'Šilutės r. sav.'),
    ('Širvintų r. sav.', 'Širvintų r. sav.'),
    ('Švenčionių r. sav.', 'Švenčionių r. sav.'),
    ('Tauragės r. sav.', 'Tauragės r. sav.'),
    ('Telšių r. sav.', 'Telšių r. sav.'),
    ('Trakų r. sav.', 'Trakų r. sav.'),
    ('Ukmergės r. sav.', 'Ukmergės r. sav.'),
    ('Utenos r. sav.', 'Utenos r. sav.'),
    ('Varėnos r. sav.', 'Varėnos r. sav.'),
    ('Vilkaviškio r. sav.', 'Vilkaviškio r. sav.'),
    ('Vilniaus m. sav.', 'Vilniaus m. sav.'),
    ('Vilniaus r. sav.', 'Vilniaus r. sav.'),
    ('Visagino sav.', 'Visagino sav.'),
    ('Zarasų r. sav.', 'Zarasų r. sav.'),
]